### ISSUE TITLE
add in testrunner support for @skip tag - we need to be able to skip a test scenario (or whole file)

### ISSUE THREAD

**Issue by EricDavisX** [elastic/e2e-testing#490]
This is from discussion with Manu off and on over a few months, we never added test runner support so here is a ticket to do the work.  hopefully small-ish effort.

A/C:
A file's main tag can be added to with @skip and the whole file will be skipped
An individual scenario's tagging can be added to with @skip and the scenario will be skipped and reported as such

**Comment by EricDavisX** [comment]
@mdelapenya hi - this doesn't sound too hard, I'd love to know more about the testrunner flow we use here. I poked into the repo and didn't discover it... if you wish, you could point me in the right direction and I could try to push it on.

**Comment by mdelapenya** [comment]
Godog supports filtering the execution by tags (See https://github.com/cucumber/godog#tags), and we are leveraging this capability in the automation in place to run thee tests.

We can filter by tags in two places:

- in the command line, with the `TAGS` environment variable:
```shell
... TAGS="fleet_mode && ~skip"...
```
- in the CI, using the `.ci/e2e-tests.yaml` file, which generates the parallel branches on CI.

```yaml
  - suite: "fleet"
    tags: "agent_endpoint_integration && ~skip"
  - suite: "fleet"
    tags: "stand_alone_mode && ~skip"
  - suite: "fleet"
    tags: "fleet_mode && ~skip"
```
