### ISSUE TITLE
Investigate why "Restarting the centos host with persistent agent restarts backend processes" fails in a consistent manner

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#785]
It does not fail in the 7.10.x branch

Example job:
- https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp%2Fmaster/detail/master/399/tests/

CI job logs:
- https://beats-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/e2e-tests/pipelines/e2e-testing-mbp/pipelines/master/runs/399/nodes/173/steps/368/log/?start=0 (Look for _"filebeat process is not running in the container yet"_)

Logs of the containers in the CI:
- https://beats-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/e2e-tests/pipelines/e2e-testing-mbp/pipelines/master/runs/399/nodes/173/steps/368/log/?start=0. 
>No elastic-agent logs are present in this file, mainly because we are not redirecting the agent output to std. See #742

**Comment by michalpristas** [comment]
this is because of a bug which was fixed but commit used is: 183fae5bb8ffbadcdde6bba0cfc28f666955896c

snapshot is old, from 15th February
```
[root@8e3c448c7452 Agent]# ./elastic-agent version
Binary: 8.0.0-SNAPSHOT (build: 183fae5bb8ffbadcdde6bba0cfc28f666955896c at 2021-02-15 15:21:19 +0000 UTC)
Daemon: 8.0.0-SNAPSHOT (build: 183fae5bb8ffbadcdde6bba0cfc28f666955896c at 2021-02-15 15:21:19 +0000 UTC)
```

the bug here is that configuration is stored without input field so nothing is started after restart
as we see using inspect


```
[root@8e3c448c7452 Agent]# ./elastic-agent inspect
Action ID: 6353df0b-db39-470d-9678-00c298a6ec15
agent:
  monitoring:
    enabled: true
    logs: true
    metrics: true
    use_output: default
fleet:
  kibana:
    hosts:
    - kibana:5601
    protocol: http
id: f3fd2d30-7283-11eb-b781-6dc5895bd2d2
outputs:
  default:
    api_key: ZCgwuXcBpVE5EmcLXhqs:LdiurJEDRN2pJlYfrwFizw
    hosts:
    - http://elasticsearch:9200
    type: elasticsearch
revision: 1
```

no inputs there as expected, so agent after restarts determines that nothing is required and test fails on missing filebeat process.

the problem will be solved once we have fresh snapshot which might be a bit delayed as for broken builds and ongoing issues

another issue causing this to occasionally fail is fixed here: https://github.com/elastic/beats/pull/24128
